
import java.util.ArrayList;
import java.lang.String;
import java.sql.Timestamp;
import java.util.Calendar;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


/**
 *
 * @author acv
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private String currentSemester; 
    
    public MainFrame() {
        initComponents();
        rebuildSemesterComboBoxes();
        rebuildStudentComboBoxes();
        rebuildCourseComboBoxes();
    }
    
    public void rebuildSemesterComboBoxes()
    {
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel(semesters.toArray()));
        if (semesters.size() > 0)
        {
            currentSemesterLabel.setText(semesters.get(0));
            currentSemester = semesters.get(0);
        }
        else
        {
            currentSemesterLabel.setText("None, add a semester.");
            currentSemester = "None";
        }
    }
    public void rebuildCourseComboBoxes()
    {
        ArrayList<String> courses= CourseQueries.getAllCourseCodes(currentSemester);
        SelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DropCourseSelectCourseCombobox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DisplayCourseListofStudentsSelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        DropCourseSelectCourseComobobox.setModel(new javax.swing.DefaultComboBoxModel(courses.toArray()));
        
        
    }
    public void rebuildStudentComboBoxes()
    {
        ArrayList<StudentEntry> students= StudentQueries.getAllStudents();
        SelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        SelectStudentScheduleComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        DropStudentSelectStudentCombobox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
        StudentDropCourseSelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel(students.toArray()));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        addSemesterTextfield = new javax.swing.JTextField();
        addSemesterSubmitButton = new javax.swing.JButton();
        addSemesterStatusLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        AdminCourseCode = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        AdminCourseDescription = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CourseSeats = new javax.swing.JSpinner();
        addCourseButton = new javax.swing.JButton();
        addCourseLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        AdminStudentID = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        AdminFirstName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        AdminLastName = new javax.swing.JTextField();
        addStudentButton = new javax.swing.JButton();
        StudentLabel = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        DisplayCourseListofStudentsSelectCourseComboBox = new javax.swing.JComboBox<>();
        DisplayCourseListofStudentsDisplayButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        DisplayCourseListofStudentsScheduledStudnetsTextArea = new javax.swing.JTextArea();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DisplayCourseListofStudentsWaitlistedStudentsTextArea = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        DropStudentSelectStudentCombobox = new javax.swing.JComboBox<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        DropStudentTextArea = new javax.swing.JTextArea();
        AdminDropStudentButton = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        DropCourseSelectCourseComobobox = new javax.swing.JComboBox<>();
        DropCourseButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        DropCourseTextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        displayCourseDisplayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        DisplayCourseTextArea = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        SelectCourseComboBox = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        SelectStudentComboBox = new javax.swing.JComboBox<>();
        displayClassesDisplayButton = new javax.swing.JButton();
        ScheduleCourseLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SelectStudentScheduleComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        DisplayScheduleTextArea = new javax.swing.JTextArea();
        DisplayScheduledisplayButton = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        DropCourseSelectCourseCombobox = new javax.swing.JComboBox<>();
        StudentDropCourseButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        StudentDropCourseTextArea = new javax.swing.JTextArea();
        StudentDropCourseSelectStudentComboBox = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        currentSemesterLabel = new javax.swing.JLabel();
        currentSemesterComboBox = new javax.swing.JComboBox<>();
        changeSemesterButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Course Scheduler");

        jLabel3.setText("Semester Name:");

        addSemesterTextfield.setColumns(20);

        addSemesterSubmitButton.setText("Submit");
        addSemesterSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSemesterSubmitButtonActionPerformed(evt);
            }
        });

        addSemesterStatusLabel.setText("                                                   ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addSemesterSubmitButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addSemesterStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(368, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(addSemesterTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSemesterSubmitButton)
                .addGap(18, 18, 18)
                .addComponent(addSemesterStatusLabel)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Add Semester", jPanel3);

        jLabel4.setText("Course Code");

        AdminCourseCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminCourseCodeActionPerformed(evt);
            }
        });

        jLabel5.setText("Course Description");

        jLabel6.setText("Seats");

        addCourseButton.setText("Submit");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AdminCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CourseSeats, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AdminCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AdminCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CourseSeats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addCourseButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(addCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
        );

        jTabbedPane2.addTab("Add Course", jPanel4);

        jLabel7.setText("Student ID:");

        AdminStudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminStudentIDActionPerformed(evt);
            }
        });

        jLabel8.setText("First Name");

        AdminFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminFirstNameActionPerformed(evt);
            }
        });

        jLabel9.setText("Last Name");

        AdminLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLastNameActionPerformed(evt);
            }
        });

        addStudentButton.setText("Submit");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StudentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AdminStudentID, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                                .addComponent(AdminFirstName)
                                .addComponent(AdminLastName)))))
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(AdminStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AdminFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(AdminLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(addStudentButton)
                .addGap(18, 18, 18)
                .addComponent(StudentLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addGap(60, 60, 60))
        );

        jTabbedPane2.addTab("Add Student", jPanel5);

        jLabel13.setText("Select Course: ");

        DisplayCourseListofStudentsSelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DisplayCourseListofStudentsSelectCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseListofStudentsSelectCourseComboBoxActionPerformed(evt);
            }
        });

        DisplayCourseListofStudentsDisplayButton.setText("Display");
        DisplayCourseListofStudentsDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayCourseListofStudentsDisplayButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Scheduled Students");

        DisplayCourseListofStudentsScheduledStudnetsTextArea.setColumns(20);
        DisplayCourseListofStudentsScheduledStudnetsTextArea.setRows(5);
        jScrollPane3.setViewportView(DisplayCourseListofStudentsScheduledStudnetsTextArea);

        jLabel16.setText("Waitlisted Students");

        DisplayCourseListofStudentsWaitlistedStudentsTextArea.setColumns(20);
        DisplayCourseListofStudentsWaitlistedStudentsTextArea.setRows(5);
        jScrollPane4.setViewportView(DisplayCourseListofStudentsWaitlistedStudentsTextArea);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DisplayCourseListofStudentsSelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                                .addComponent(DisplayCourseListofStudentsDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(226, 226, 226))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(DisplayCourseListofStudentsSelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DisplayCourseListofStudentsDisplayButton))
                .addGap(42, 42, 42)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Display Course List of Students", jPanel9);

        jLabel17.setText("Select Student");

        DropStudentSelectStudentCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DropStudentSelectStudentCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropStudentSelectStudentComboboxActionPerformed(evt);
            }
        });

        DropStudentTextArea.setColumns(20);
        DropStudentTextArea.setRows(5);
        jScrollPane5.setViewportView(DropStudentTextArea);

        AdminDropStudentButton.setText("Drop Student");
        AdminDropStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminDropStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(AdminDropStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DropStudentSelectStudentCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(DropStudentSelectStudentCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(AdminDropStudentButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Student", jPanel10);

        jLabel18.setText("Select Course to be Dropped:");

        DropCourseSelectCourseComobobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DropCourseSelectCourseComobobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseSelectCourseComoboboxActionPerformed(evt);
            }
        });

        DropCourseButton.setText("Drop Course");
        DropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseButtonActionPerformed(evt);
            }
        });

        DropCourseTextArea.setColumns(20);
        DropCourseTextArea.setRows(5);
        jScrollPane6.setViewportView(DropCourseTextArea);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(DropCourseSelectCourseComobobox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(DropCourseButton)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DropCourseSelectCourseComobobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DropCourseButton))
                    .addComponent(jLabel18))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Drop Course", jPanel11);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Admin", jPanel1);

        displayCourseDisplayButton.setText("Display");
        displayCourseDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayCourseDisplayButtonActionPerformed(evt);
            }
        });

        DisplayCourseTextArea.setColumns(20);
        DisplayCourseTextArea.setRows(5);
        jScrollPane1.setViewportView(DisplayCourseTextArea);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(displayCourseDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayCourseDisplayButton))
        );

        jTabbedPane3.addTab("Display Courses", jPanel6);

        jLabel11.setText("Schedule Course:");

        SelectCourseComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectCourseComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectCourseComboBoxActionPerformed(evt);
            }
        });

        jLabel12.setText("Select Student:");

        SelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectStudentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectStudentComboBoxActionPerformed(evt);
            }
        });

        displayClassesDisplayButton.setText("Submit");
        displayClassesDisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayClassesDisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(displayClassesDisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(40, 40, 40)
                                .addComponent(SelectCourseComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(51, 51, 51)
                                .addComponent(SelectStudentComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(ScheduleCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(330, 330, 330))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SelectCourseComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(SelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(displayClassesDisplayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(ScheduleCourseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );

        jTabbedPane3.addTab("Schedule Classes", jPanel7);

        jLabel14.setText("Select Student:");

        SelectStudentScheduleComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SelectStudentScheduleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectStudentScheduleComboBoxActionPerformed(evt);
            }
        });

        DisplayScheduleTextArea.setColumns(20);
        DisplayScheduleTextArea.setRows(5);
        jScrollPane2.setViewportView(DisplayScheduleTextArea);

        DisplayScheduledisplayButton.setText("Display");
        DisplayScheduledisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayScheduledisplayButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SelectStudentScheduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(DisplayScheduledisplayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(SelectStudentScheduleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DisplayScheduledisplayButton)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Display Schedule", jPanel8);

        jLabel19.setText("Select Course:");

        DropCourseSelectCourseCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        DropCourseSelectCourseCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DropCourseSelectCourseComboboxActionPerformed(evt);
            }
        });

        StudentDropCourseButton.setText("Drop Course");
        StudentDropCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDropCourseButtonActionPerformed(evt);
            }
        });

        StudentDropCourseTextArea.setColumns(20);
        StudentDropCourseTextArea.setRows(5);
        jScrollPane7.setViewportView(StudentDropCourseTextArea);

        StudentDropCourseSelectStudentComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        StudentDropCourseSelectStudentComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentDropCourseSelectStudentComboBoxActionPerformed(evt);
            }
        });

        jLabel20.setText("Select Student");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StudentDropCourseSelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DropCourseSelectCourseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(StudentDropCourseButton)
                .addGap(110, 110, 110))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(DropCourseSelectCourseCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(StudentDropCourseButton)
                    .addComponent(StudentDropCourseSelectStudentComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Drop Course", jPanel12);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3))
        );

        jTabbedPane1.addTab("Student", jPanel2);

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel2.setText("Current Semester: ");

        currentSemesterLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        currentSemesterLabel.setText("           ");

        currentSemesterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        currentSemesterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentSemesterComboBoxActionPerformed(evt);
            }
        });

        changeSemesterButton.setText("Change Semester");
        changeSemesterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeSemesterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentSemesterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(changeSemesterButton)
                                .addGap(80, 80, 80)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(currentSemesterLabel)
                    .addComponent(currentSemesterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(changeSemesterButton)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addSemesterSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSemesterSubmitButtonActionPerformed
        String semester = addSemesterTextfield.getText();
        SemesterQueries.addSemester(semester);
        addSemesterStatusLabel.setText("Semester " + semester + "  has been added.");
        rebuildSemesterComboBoxes();
    }//GEN-LAST:event_addSemesterSubmitButtonActionPerformed

    private void displayCourseDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayCourseDisplayButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<CourseEntry> courses = CourseQueries.getAllCourses(currentSemester);
        DisplayCourseTextArea.setText("Course Code\tSeats\tDescription\n");
        for(CourseEntry course : courses){
            DisplayCourseTextArea.append(course.getCourseCode()+"\t"+course.getSeats()+"\t"+course.getCourseDescription()+"\n");
            
        }
    }//GEN-LAST:event_displayCourseDisplayButtonActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        // TODO add your handling code here:
        String courseCode = AdminCourseCode.getText();
        String description =AdminCourseDescription.getText();
        int seats = (Integer)(CourseSeats.getValue());
        CourseEntry course = new CourseEntry(currentSemester,courseCode,description,seats);
        CourseQueries.addCourse(course);
        addCourseLabel.setText(courseCode+" has been added");
        rebuildCourseComboBoxes();
        
        
        
        
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void currentSemesterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentSemesterComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currentSemesterComboBoxActionPerformed

    private void AdminCourseCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCourseCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminCourseCodeActionPerformed

    private void AdminStudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminStudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminStudentIDActionPerformed

    private void AdminLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminLastNameActionPerformed

    private void AdminFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdminFirstNameActionPerformed

    private void SelectCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectCourseComboBoxActionPerformed
        // TODO add your handling code here:
        
            
        
    }//GEN-LAST:event_SelectCourseComboBoxActionPerformed

    private void displayClassesDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayClassesDisplayButtonActionPerformed
        // TODO add your handling code here:
        String semester = currentSemesterComboBox.getSelectedItem().toString();
        String allCourseCodes = SelectCourseComboBox.getSelectedItem().toString();
        ArrayList<StudentEntry>students=StudentQueries.getAllStudents();
        String studentID  =students.get(SelectStudentComboBox.getSelectedIndex()).getStudentID();
        ArrayList<ScheduleEntry>studentSchedule=ScheduleQueries.getScheduleByStudent(semester, studentID);
        String firstName = students.get(SelectStudentComboBox.getSelectedIndex()).getFirstName();
        String lastName = students.get(SelectStudentComboBox.getSelectedIndex()).getLastName();
        int seats =CourseQueries.getCourseSeats(semester,allCourseCodes);
        int returnseats = ScheduleQueries.getScheduledStudentCount(semester, allCourseCodes);
        Timestamp timestamp = new java.sql.Timestamp(Calendar.getInstance().getTime().getTime());
        if (seats > returnseats){
            ScheduleEntry schedule = new ScheduleEntry(semester,allCourseCodes,studentID,"Scheduled",timestamp);
            ScheduleCourseLabel.setText(lastName+","+firstName+" has been added.");
            ScheduleQueries.addScheduleEntry(schedule);
        }
        else{
            ScheduleEntry schedule= new ScheduleEntry(semester,allCourseCodes,studentID,"Waitlisted",timestamp);
            ScheduleQueries.addScheduleEntry(schedule);
            ScheduleCourseLabel.setText(lastName+","+firstName+" has been waitlisted for the class.");
        }
    }//GEN-LAST:event_displayClassesDisplayButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        // TODO add your handling code here:
        String studentID=AdminStudentID.getText();
        String firstName= AdminFirstName.getText();
        String lastName= AdminLastName.getText();
        StudentEntry student = new StudentEntry(studentID,firstName,lastName);
        StudentQueries.addStudent(student);
        StudentLabel.setText(lastName+","+firstName+"  has been added.");
        rebuildStudentComboBoxes();
        
        
        
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void changeSemesterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeSemesterButtonActionPerformed
        // TODO add your handling code here:
        String Semester = currentSemesterComboBox.getSelectedItem().toString();
        currentSemesterLabel.setText(Semester);
        currentSemester=Semester;
        rebuildCourseComboBoxes();
        
        
    }//GEN-LAST:event_changeSemesterButtonActionPerformed

    private void SelectStudentScheduleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectStudentScheduleComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectStudentScheduleComboBoxActionPerformed

    private void DisplayScheduledisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayScheduledisplayButtonActionPerformed
        // TODO add your handling code here:
        
        // TODO add your handling code here:
        ArrayList<StudentEntry>student = StudentQueries.getAllStudents();
        String studentID = student.get(SelectStudentScheduleComboBox.getSelectedIndex()).getStudentID();
        
        ArrayList<ScheduleEntry>schedule = ScheduleQueries.getScheduleByStudent(currentSemester, studentID);
        DisplayScheduleTextArea.setText("Course Code\tStatus\n");
        for(ScheduleEntry entry: schedule){
            DisplayScheduleTextArea.append(entry.getCoursecode()+"\t"+entry.getS()+"\n");
            
        }
        
    }//GEN-LAST:event_DisplayScheduledisplayButtonActionPerformed

    private void DisplayCourseListofStudentsSelectCourseComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseListofStudentsSelectCourseComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DisplayCourseListofStudentsSelectCourseComboBoxActionPerformed

    private void DropCourseSelectCourseComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseSelectCourseComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropCourseSelectCourseComboboxActionPerformed

    private void DropCourseSelectCourseComoboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseSelectCourseComoboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropCourseSelectCourseComoboboxActionPerformed

    private void DropStudentSelectStudentComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropStudentSelectStudentComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DropStudentSelectStudentComboboxActionPerformed

    private void SelectStudentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectStudentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectStudentComboBoxActionPerformed

    private void StudentDropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDropCourseButtonActionPerformed
        // TODO add your handling code here:
        String currsemester = currentSemesterComboBox.getSelectedItem().toString();
        ArrayList<StudentEntry> students =StudentQueries.getAllStudents();
        String studentID = students.get(StudentDropCourseSelectStudentComboBox.getSelectedIndex()).getStudentID();
        
        String studentname = students.get(StudentDropCourseSelectStudentComboBox.getSelectedIndex()).toString();
        String courseCode = DropCourseSelectCourseCombobox.getSelectedItem().toString();
        
        ScheduleQueries.dropStudentScheduleByCourse(currsemester, studentID,courseCode);
        StudentDropCourseTextArea.setText(studentname+" "+studentID+" has been dropped from "+courseCode+"\n");
        
        ArrayList<ScheduleEntry> waitlisted = ScheduleQueries.getWaitlistedStudentsByCourse(currsemester, courseCode);
        if(!waitlisted.isEmpty()){
            ScheduleQueries.updateScheduleEntry(currsemester, waitlisted.get(0));
            StudentEntry waitlist = StudentQueries.getStudent(waitlisted.get(0).getStudentID());
            System.out.println(waitlisted.get(0).getStudentID().toString());
            StudentDropCourseTextArea.append(waitlist.getFirstName()+","+waitlist.getLastName()+" "+waitlist.getStudentID()+" has been scheduled into " +courseCode +"\n");
        }
    }//GEN-LAST:event_StudentDropCourseButtonActionPerformed

    private void DropCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DropCourseButtonActionPerformed
        // TODO add your handling code here:
        
        String courseCode = DropCourseSelectCourseComobobox.getSelectedItem().toString();
        ArrayList<ScheduleEntry>scheduled=ScheduleQueries.getScheduledStudentsByCourse(currentSemester, courseCode);
        DropCourseTextArea.append("Scheduled Students dropped from the course:\n");
        
        for (ScheduleEntry entry : scheduled){
            
            
            StudentEntry schedule = StudentQueries.getStudent(entry.getStudentID());
            
            
         DropCourseTextArea.append(schedule.getFirstName()+","+schedule.getLastName()+" "+schedule.getStudentID()+"\n"); 
         
        }
        ArrayList<ScheduleEntry>waitlist = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);
        DropCourseTextArea.append("\nWaitlisted Students dropped from the course:\n");
        for (ScheduleEntry entry:waitlist){
            StudentEntry schedule =StudentQueries.getStudent(entry.getStudentID());
            
            DropCourseTextArea.append(schedule.getFirstName()+","+schedule.getLastName()+" "+schedule.getStudentID()+"\n");
        }
        ScheduleQueries.dropScheduleByCourse(currentSemester, courseCode);
        CourseQueries.dropCourse(currentSemester, courseCode);
        rebuildCourseComboBoxes();
    }//GEN-LAST:event_DropCourseButtonActionPerformed

    private void DisplayCourseListofStudentsDisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayCourseListofStudentsDisplayButtonActionPerformed
        // TODO add your handling code here:
        String courseCode =DisplayCourseListofStudentsSelectCourseComboBox.getSelectedItem().toString();
        ArrayList<ScheduleEntry> scheduled = ScheduleQueries.getScheduledStudentsByCourse(currentSemester, courseCode);
        DisplayCourseListofStudentsScheduledStudnetsTextArea.setText("LastName\t FirstName\t StudentID \n");
        
        for (ScheduleEntry entry :scheduled){
            String studentID= entry.getStudentID();
            StudentEntry studente = StudentQueries.getStudent(studentID);
            String firstname = studente.getFirstName();
            String lastname = studente.getLastName();
            DisplayCourseListofStudentsScheduledStudnetsTextArea.append(lastname + "\t"+firstname +"\t"+studentID+"\n");
            
        }
        ArrayList<ScheduleEntry> waitlisted = ScheduleQueries.getWaitlistedStudentsByCourse(currentSemester, courseCode);
        DisplayCourseListofStudentsWaitlistedStudentsTextArea.setText("LastName\t FirstName\t StudentID \n");
        
        for (ScheduleEntry entry :waitlisted){
            
            
            
            String studentID= entry.getStudentID();
            
            StudentEntry studente = StudentQueries.getStudent(studentID);
            
            String firstname = studente.getFirstName();
            String lastname = studente.getLastName();
            DisplayCourseListofStudentsWaitlistedStudentsTextArea.append(lastname + "\t"+firstname +"\t"+studentID+"\n");
            
        }    
    }//GEN-LAST:event_DisplayCourseListofStudentsDisplayButtonActionPerformed

    private void AdminDropStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminDropStudentButtonActionPerformed
        // TODO add your handling code here:
        ArrayList<String> semesters = SemesterQueries.getSemesterList();
        ArrayList<StudentEntry> students =StudentQueries.getAllStudents();
        String studentID = students.get(DropStudentSelectStudentCombobox.getSelectedIndex()).getStudentID();
        String firstname =students.get(DropStudentSelectStudentCombobox.getSelectedIndex()).getFirstName();
        String lastname =students.get(DropStudentSelectStudentCombobox.getSelectedIndex()).getLastName();
        StudentQueries.dropStudent(studentID);
        DropStudentTextArea.append(firstname + ","+lastname+" "+studentID+" has been dropped from the list of students.");
        rebuildStudentComboBoxes();
        
        
        for (String s: semesters){
            ArrayList<ScheduleEntry>schedule = ScheduleQueries.getScheduleByStudent(s,studentID);
            DropStudentTextArea.append("\n For Smester "+s+"\n");
            for (ScheduleEntry entry:schedule){
                String status = entry.getS();
                
                String CourseCode =entry.getCoursecode();
                ArrayList<ScheduleEntry> waitlisted =ScheduleQueries.getWaitlistedStudentsByCourse(s, CourseCode);
                if ("Scheduled".equals(status)){
                    ScheduleQueries.dropStudentScheduleByCourse(s, entry.getStudentID(), entry.getCoursecode());
                    DropStudentTextArea.append(firstname+" "+lastname+" "+" has been dropped from"+ CourseCode+"\n");
                
                
                if (!waitlisted.isEmpty()){
                    ScheduleQueries.updateScheduleEntry(s,waitlisted.get(0));
                    StudentEntry waitlist = StudentQueries.getStudent(waitlisted.get(0).getStudentID());
                    
                    DropStudentTextArea.append(waitlist.getFirstName()+","+waitlist.getLastName()+" "+waitlist.getStudentID()+"has been scheduled into"+CourseCode+"\n");
                    
                
                } 
            }
            else{
                    ScheduleQueries.dropStudentScheduleByCourse(s, entry.getStudentID() , entry.getCoursecode());
                    DropStudentTextArea.append(firstname+","+lastname+" "+studentID+" has been dropped from the waitlist for"+CourseCode+"\n");
                    }
            
            }}
    }//GEN-LAST:event_AdminDropStudentButtonActionPerformed

    private void StudentDropCourseSelectStudentComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentDropCourseSelectStudentComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentDropCourseSelectStudentComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AdminCourseCode;
    private javax.swing.JTextField AdminCourseDescription;
    private javax.swing.JButton AdminDropStudentButton;
    private javax.swing.JTextField AdminFirstName;
    private javax.swing.JTextField AdminLastName;
    private javax.swing.JTextField AdminStudentID;
    private javax.swing.JSpinner CourseSeats;
    private javax.swing.JButton DisplayCourseListofStudentsDisplayButton;
    private javax.swing.JTextArea DisplayCourseListofStudentsScheduledStudnetsTextArea;
    private javax.swing.JComboBox<String> DisplayCourseListofStudentsSelectCourseComboBox;
    private javax.swing.JTextArea DisplayCourseListofStudentsWaitlistedStudentsTextArea;
    private javax.swing.JTextArea DisplayCourseTextArea;
    private javax.swing.JTextArea DisplayScheduleTextArea;
    private javax.swing.JButton DisplayScheduledisplayButton;
    private javax.swing.JButton DropCourseButton;
    private javax.swing.JComboBox<String> DropCourseSelectCourseCombobox;
    private javax.swing.JComboBox<String> DropCourseSelectCourseComobobox;
    private javax.swing.JTextArea DropCourseTextArea;
    private javax.swing.JComboBox<String> DropStudentSelectStudentCombobox;
    private javax.swing.JTextArea DropStudentTextArea;
    private javax.swing.JLabel ScheduleCourseLabel;
    private javax.swing.JComboBox<String> SelectCourseComboBox;
    private javax.swing.JComboBox<String> SelectStudentComboBox;
    private javax.swing.JComboBox<String> SelectStudentScheduleComboBox;
    private javax.swing.JButton StudentDropCourseButton;
    private javax.swing.JComboBox<String> StudentDropCourseSelectStudentComboBox;
    private javax.swing.JTextArea StudentDropCourseTextArea;
    private javax.swing.JLabel StudentLabel;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JLabel addCourseLabel;
    private javax.swing.JLabel addSemesterStatusLabel;
    private javax.swing.JButton addSemesterSubmitButton;
    private javax.swing.JTextField addSemesterTextfield;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton changeSemesterButton;
    private javax.swing.JComboBox<String> currentSemesterComboBox;
    private javax.swing.JLabel currentSemesterLabel;
    private javax.swing.JButton displayClassesDisplayButton;
    private javax.swing.JButton displayCourseDisplayButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    // End of variables declaration//GEN-END:variables
}
